package engine.main;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.List;

import engine.meta.GrammarParser;
import engine.meta.Production;


public class Main {

	public static void main(String args[]) throws Exception{
		
		AssociationsManager am = new AssociationsManager();
		BufferedReader br = new BufferedReader(new InputStreamReader(System.in)); 
		GrammarParser grammarParser = new GrammarParser("grammar.xml");
		Production startTag = grammarParser.getProduction("start");
		if(startTag.isAutoGenerated){
			System.out.println(startTag.value);
			System.out.println(startTag.next);
		}
		String readLine = null;
		List<String> context = startTag.next;
		while((readLine = br.readLine())!= null){
			if(readLine.startsWith("KNOWLEDGE:")){
				
			}
			System.out.println(readLine);
			String matchedConstruct=am.findConstruct(readLine, context);
			System.out.println("matched "+matchedConstruct);
			Production prod = grammarParser.getProduction(matchedConstruct);
			System.out.println(prod.components);
			for(String component:prod.components){
				System.out.print(am.getBestComponentChoice(grammarParser.getProduction(component),component));
			}
		}
	}

}
