package engine.main;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.List;

import org.apache.log4j.Logger;

import engine.meta.GrammarParser;
import engine.meta.Production;


public class Main {

	private static Logger logger = Logger.getLogger(Main.class);
	public static void main(String args[]) throws Exception{

		AssociationsManager am = new AssociationsManager();
		BufferedReader br = new BufferedReader(new InputStreamReader(System.in)); 
		GrammarParser grammarParser = new GrammarParser("grammar.xml");
		Production startTag = grammarParser.getProduction("start");
		if(startTag.isAutoGenerated){
			logger.debug(startTag.value);
			logger.debug(startTag.next);
		}
		String readLine = null;
		List<String> context = startTag.next;
		while((readLine = br.readLine())!= null){
			if(readLine.startsWith("KNOWLEDGE:")){
				
			}
			logger.debug(readLine);
			String matchedConstruct=am.findConstruct(readLine, context);
			logger.debug("matched "+matchedConstruct);
			Production prod = grammarParser.getProduction(matchedConstruct);
			logger.debug(prod.components);
			for(String component:prod.components){
				System.out.print(am.getBestComponentChoice(grammarParser.getProduction(component),component));
			}
		}
	}

}
